# Generated by Django 5.1.4 on 2025-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_moodentry_user_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
